### ISSUE TITLE
Tela de divugação de produtos do marolo

### ISSUE THREAD

**Issue by henriquejensen** [grupythonUFLA/marolo#10]
Criar uma pagina para divulgar os produtos feitos pela associação com marolo.
Divulgação apenas com imagens e descrição do produto

**Comment by pvsousalima** [comment]
Verificar commit ba0900d86

**Comment by cassiobotaro** [comment]
Acho que podemos criar o modelo da página para torna-la dinâmica(ver #55 )

**Comment by cassiobotaro** [comment]
Dado que o commit já foi integrado ao sistema, podemos agora abrir nova issue para colocarmos a página dinâmica.
