### ISSUE TITLE
Novo modelo para membros enriquecida

### ISSUE THREAD

**Issue by cassiobotaro** [grupythonUFLA/marolo#127]
Sugestão de novo modelo para os membros para tornar a tela mais enruiceda, lógico, seguinda as cores do layout atual.
http://bootsnipp.com/snippets/featured/dynamic-avatar-blur

**Comment by henriquejensen** [comment]
tem este estilo tbm
http://bootsnipp.com/snippets/featured/profile-card

**Comment by cassiobotaro** [comment]
Minha sugestão foi baseada no modelo atual de membros, esta nova opção resultaria em uma nova modelagem dos membros.
