### ISSUE TITLE
Tela Notícias

### ISSUE THREAD

**Issue by cassiobotaro** [grupythonUFLA/marolo#13]
Aplicar estilo à tela de notícia(individual).

**Comment by pvsousalima** [comment]
Vou pegar. Estilo padrão de visualização das notícias?

**Comment by thiagopnobre** [comment]
Isso, tenta fazer algo no padrão das outras telas. E acho que dá para aproveitar e resolver junto a issue #79. O que acham?

**Comment by cassiobotaro** [comment]
sim, tem que ser resolvido junto com issu #79
