### ISSUE TITLE
Atualizar ckeditor

### ISSUE THREAD

**Issue by cassiobotaro** [grupythonUFLA/marolo#15]
Já existe versão mais nova no web2py slice

**Comment by cassiobotaro** [comment]
Versão atualizada do site e remover arquivos desnecessários do plugin

**Comment by cassiobotaro** [comment]
O que acham de dermos um fork do projeto e atualizarmos o plugin?

**Comment by henriquejensen** [comment]
este http://www.web2pyslices.com/slice/show/1952/ck-editor4-plugin @cassiobotaro  ?

**Comment by cassiobotaro** [comment]
https://github.com/timrichardson/web2py_ckeditor4
