### ISSUE TITLE
Corrigir problemas na tela "Esqueceu a senha?" do admin

### ISSUE THREAD

**Issue by thiagopnobre** [grupythonUFLA/marolo#153]
Ao tentar utilizar a opção de "Esqueceu a senha?" na tela de login do admin, redireciona-se para a página de "Redefinir Senha" (request_reset_password), mas ao chegar lá, quando tenta-se de fato redefinir a senha, um ticket de erro é gerado.

A mensagem de erro contida no ticket é: <type 'exceptions.Exception'> Server address not specified

Dica: Apesar de haverem configurações de e-mail para a tela de contato, como é utilizado um esquema de modelo condicional, aparentemente faltam as configurações de e-mail para a tela request_reset_password do controller admin.

**Comment by cassiobotaro** [comment]
Corrigido com 348ff6a9566a4e98715577d7511a4da9410aba10
