### ISSUE TITLE
Popular banco de dados

### ISSUE THREAD

**Issue by cassiobotaro** [grupythonUFLA/marolo#29]
É necessário popular o banco de dados com valores para testes.
Existem duas alternativas, compartilhamento de xml e sua eventual importação a cada nova instalação, ou criar um script para popular o banco rodando somente uma vez.

**Comment by thiagopnobre** [comment]
Talvez um script para fazer um bulk insert usando algo como o LOAD DATA INFILE carregando um arquivo CSV ou algo do tipo seja uma boa ideia, já que o bulk insert provavelmente é otimizado.

**Comment by cassiobotaro** [comment]
Acho que a solução foi satisfatória e em conversa com @thiagopnobre , concluimos que esta issue pode ser concluída.
