### ISSUE TITLE
Estilo menu admin

### ISSUE THREAD

**Issue by cassiobotaro** [grupythonUFLA/marolo#3]
Corrigir estilo do menu no template de admin.

**Comment by henriquejensen** [comment]
closed this in #8b72c4f

**Comment by cassiobotaro** [comment]
Ainda tá cinza =/ Utilizo chrome na ultima versão.

**Comment by cassiobotaro** [comment]
Uma dica do estilo que está fazendo o layout quebrar
![captura de tela_2015-08-26_00-13-44](https://cloud.githubusercontent.com/assets/3127847/9484810/632b9b26-4b87-11e5-905d-86f4ab92ddf5.png)
