### ISSUE TITLE
Adicionar screenshot do projeto

### ISSUE THREAD

**Issue by cassiobotaro** [grupythonUFLA/marolo#47]
Adicionar ao README screenshot do projeto e criação de site do projeto.
Adicionar screenshot do projeto em versão atual e atualizar quando houver melhorias, principalmente de front-end.

**Comment by henriquejensen** [comment]
screenshot com noticias proximas do real do site? acho que seriam mais interessantes

**Comment by cassiobotaro** [comment]
pensei em fazer histórico de evolução

**Comment by cassiobotaro** [comment]
Interessante a contribuição do @pvsousalima 4bbd9b75e

**Comment by pvsousalima** [comment]
Com certeza, seria um gif para cada tela?

**Comment by cassiobotaro** [comment]
Talvez não gif em todas as telas, faz screenshot e daqui um tempo fazemos novo e um gif com os dois.
