### ISSUE TITLE
Ajustar a localizacao dos patrocinadores

### ISSUE THREAD

**Issue by henriquejensen** [grupythonUFLA/marolo#49]
Patrocinadores estao aparecendo em ultimo em paginas menores que 990px, eles devem aparecer antes dos parceiros

**Comment by cassiobotaro** [comment]
Já foi resolvido @henriquejensen ?

**Comment by henriquejensen** [comment]
Ainda não, as ideias que tive não deram certo, vou ver se consigo sem alterar tanto o código
