### ISSUE TITLE
Noticias mostradas na ordem contraria

### ISSUE THREAD

**Issue by henriquejensen** [grupythonUFLA/marolo#53]
As noticias inseridas no site estao aparecendo na ordem inversa da comum (estao do mais antigo para o mais novo) na pagina inicial

**Comment by cassiobotaro** [comment]
VI que teve um commit relacionado(8b72c) Que tal reimplementarmos esta inversão na consulta ao banco de dados e já paginarmos a index?

**Comment by henriquejensen** [comment]
Acho mais interessante pelo banco tbm. Colocar umas 10 noticias por pagina?
