### ISSUE TITLE
Script para instalação e povoamento do banco de dados

### ISSUE THREAD

**Issue by pvsousalima** [grupythonUFLA/marolo#73]
Sugestão de um script para povoamento do banco de dados e cópia do appconfig.ini do welcome para a pasta do maroto automaticamente. Também poderia vir a instalar todas as dependências necessárias do projeto de forma automática.

**Comment by cassiobotaro** [comment]
:+1:

**Comment by cassiobotaro** [comment]
#74 deve ser adicionado ao script

**Comment by cassiobotaro** [comment]
#33 também deve ser incluído.
