### ISSUE TITLE
Sem feedback admin

### ISSUE THREAD

**Issue by cassiobotaro** [grupythonUFLA/marolo#77]
Flash deve ser adicionado também à template do admin.
Mensagens de feedback são necessárias.

**Comment by thiagopnobre** [comment]
Ok, vou resolver isso. Não tinha visto que eram dois layouts html, um para o site e um para o admin, independentes.

**Comment by cassiobotaro** [comment]
Talvez um base geral e dois layouts diferentes a partir do base. 
Deixao menu por exemplo como um bloco.
