### ISSUE TITLE
Ajustar idioma de algumas funcoes

### ISSUE THREAD

**Issue by henriquejensen** [grupythonUFLA/marolo#95]
na funcao editar do admin, a funcionalidade deletar esta escrita em ingles, como o site esta em portugues esta funcao nao esta no padrao

![mudar](https://cloud.githubusercontent.com/assets/4885094/9721612/46fb4388-5574-11e5-95d5-18a9eb49ca48.png)

**Comment by cassiobotaro** [comment]
T.force('pt-br')
Mas precisa estar com o idioma na pasta languages
E se tem palavras ainda sem tradução
